### ISSUE TITLE
GPU: Intel only

### ISSUE THREAD

**Issue by WizardCM** [sophieschi/loganalyzer#2]
Logs that only contain a single Intel graphics card don't provide a warning.

https://gist.github.com/anonymous/76bcaea8bcbb3671c2c44791da7543f0

(Should I also make a issue for this one that an i3 is underpowered and we should account for that, or would it be part of a fix for Intel only GPU?

**Comment by sophieschi** [comment]
I'll output a warning for iGPU and an info of i3.
